cart/urls.py
from django.conf.urls import url
from .views import cart_add,cart_remove,cart_detail

app_name = 'cart'

urlpatterns = [
    url(r'^$', cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', cart_remove, name='cart_remove'),
]

eCommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('cart', include('cart.urls')),
    path('orders/', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url
from .views import order_create

app_name = 'orders'

urlpatterns =[
    url(r'^create/$', order_create, name='order_create')
]

shop/urls.py
from django.conf.urls import url
from .views import product_list, product_detail, register, log_in, log_out, story

app_name = 'shop'

urlpatterns = [
    url(r'^$', product_list, name='product_list'),  # $:End of string 
    url(r'^(?P<category_slug>[-\w]+)/$', product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', product_detail, name='product_detail'),
    url(r'^register$', register, name='register'),
    url(r'^logout$', log_out, name='logout'),
    url(r'^login$', log_in, name='login'),
    url(r'^story$', story, name='story')
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1,26)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])

    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart/detail.html', 
                  {'cart': cart})

cart/templates/cart/detail.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart
{% endblock %}

{% block content %}
    <div class="container-fluid h-100">
        <div class="row h-100" style="margin-top: 5%; margin-bottom: 0">
        <h2>Your Shopping Cart
            <span class="badge pull-right"  style="font-size: 24px; font-weight: 300">
                {% with totail_items=cart|length %}
                    {% if cart|length > 0 %}
                        <a href="{% url "cart:cart_detail" %}" style="color: #ffffff">
                        My Shopping Order:{{ totail_items }} item {{ totail_items|pluralize }}, USD $ {{ cart.get_total_price }}
                        </a>
                        {% else %}
                        Your cart is empty.
                    {% endif %}
                {% endwith %}
            </span>
        </h2>
            <table class="table table-striped table-hover" style="font-size: 24px; font-weight: 200">
                <thead style="background-color: #5AC8FA">
                    <tr>
                        <th>Image</th>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Remove</th>
                        <th>Unit Price</th>
                        <th>Price</th>
                    </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                    {% with product=item.product  %}
                        <tr>
                            <td>
                                <a href="{{ product.get_absolute_url }}">
                                    <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 130px; width: auto">
                                </a>
                            </td>
                            <td>{{ product.name }}</td>
                            <td>
                                <form action="{% url "cart:cart_add" product.id %}" method="post">
                                    {% csrf_token %}
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.update }}
                                    <input type="submit" value="Update" class="btn btn-info">
                                </form>
                            </td>
                            <td>
                                <a href="{% url "cart:cart_remove" product.id %}">Remove</a>
                            </td>
                            <td>USD. {{ item.price }}</td>
                            <td>USD. {{ item.total_price }}</td>
                        </tr>
                    {% endwith %}
                {% endfor %}
                <tr style="background-color: #5AC8FA">
                    <td><b>Total</b></td>
                    <td colspan="4"></td>
                    <td colspan="num"><b>USD $ {{ cart.get_total_price }}</b></td>
                </tr>
                </tbody>
            </table>
        <p class="text-right">
            <a href="{% url "shop:product_list" %}" class="btn btn-default"  style="font-size: 24px; font-weight: 300">Continue Shopping</a>
            <a href="{% url "orders:order_create" %}" class="btn btn-primary"  style="font-size: 24px; font-weight: 300">Checkout</a>
        </p>
        </div>
    </div>
{% endblock %}