cart/urls.py
from django.conf.urls import url
from .views import cart_add,cart_remove,cart_detail

app_name = 'cart'

urlpatterns = [
    url(r'^$', cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', cart_remove, name='cart_remove'),
]

eCommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('cart', include('cart.urls')),
    path('orders/', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import url
from .views import product_list, product_detail, register, log_in, log_out, story

app_name = 'shop'

urlpatterns = [
    url(r'^$', product_list, name='product_list'),  # $:End of string 
    url(r'^(?P<category_slug>[-\w]+)/$', product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', product_detail, name='product_detail'),
    url(r'^register$', register, name='register'),
    url(r'^logout$', log_out, name='logout'),
    url(r'^login$', log_in, name='login'),
    url(r'^story$', story, name='story')
]

shop/models.py
from django.urls import reverse
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True) # Typically, only the primary key is indexed by the database. This means look ups using the primary key are optimized.
    slug = models.SlugField(max_length=150, unique=150, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name ='category'
        verbose_name_plural ='categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args= [self.slug] )

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d',blank=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id','slug'))

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_detail',
                        args=[self.id, self.slug])

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, Product 
from cart.forms import CartAddProductForm
from django.contrib.auth import login,logout, authenticate
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages

def product_list(request, category_slug = None ): 
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)

    context = {    # containing the data to insert into the placeholders. 
        'category': category,
        'categories': categories,
        'products': products
    }
    

    return render(request, 'shop/product/list.html', context)

def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, available=True)
    cart_product_form = CartAddProductForm()

    categories = Category.objects.all()
    
    context = {  # containing the data to insert into the placeholders. 
        'product': product,
        'cart_product_form': cart_product_form,
        'categories': categories
    }

    return render(request, 'shop/product/detail.html', context)
    

def log_in(request):
    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('/')
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(request, 'shop/login.html', {'form': form})



def register(request):
    if request.method == 'POST':

    	# Assigning the User Creation form with the Post request object to form variable
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # Save the user
            form.save()
            # Getting the values from the form
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            # Authenticate user using the authenticate method
            user = authenticate(username=username, password=raw_password)

            # After Successfully Authenticated then use login function to login the user

            login(request, user)
            return redirect('/')
    else:
        form = UserCreationForm()
    return render(request, 'shop/signup.html', {'form': form})


def log_out(request):
    logout(request)
    return redirect('/')


@login_required(login_url='/login')
def story(request):
    return render(request, 'shop/story.html', {})

shop/templates/shop/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}On-line Shop{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    

    <link href="https://fonts.googleapis.com/css?family=Cinzel+Decorative&display=swap" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" rel="stylesheet">

</head>
<body>
{% include 'shop/navbar.html' %}

<div class="container">
    <div class="row" style="margin-top: 6%">
         <button class="btn btn-info pull-right" style="font-size: 24px; font-weight: 400">
            {% with totail_items=cart|length %}
                {% if cart|length > 0 %}
                    <a href="{% url "cart:cart_detail" %}" style="color: #ffffff">
                    My Shopping Order:{{ totail_items }} item {{ totail_items|pluralize }}, USD $ {{ cart.get_total_price }}
                    </a>
                    {% else %}
                    Your cart is empty.
                {% endif %}
            {% endwith %}
            <i class="fa fa-shopping-cart" aria-hidden="true"></i>
         </button>
    </div>
</div>

{% block content %}
{% endblock %}


{% include 'shop/footer.html' %}

<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>

</body>
</html>

shop/templates/shop/footer.html
<!-- Footer -->
<footer class="page-footer font-small cyan darken-3">

  <!-- Footer Elements -->
  <div class="container-fluid h-100">

    <!-- Grid row-->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-12 text-center py-5 ">
        <div class="mb-5 flex-center">
            <a class="fb-ic" href="https://www.facebook.com/ponponchiao/">
              <i class="fab fa-facebook-f fa-lg white-text mr-md-5 mr-3 fa-2x" style="color:#004d8c; height:fit-content"> </i>
            </a>
            <a class="ins-ic" href="https://www.instagram.com/ponponchiao/">
              <i class="fab fa-instagram fa-lg white-text mr-md-5 mr-3 fa-2x" style="color:#004d8c; height:fit-content"> </i>
            </a>
        </div>
      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row-->

  </div>
  <!-- Footer Elements -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="#" style="color:#004d8c">  Shang-Wei Hung</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

shop/templates/shop/login.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
    {% if category %}
        {{ category.name }} 
    {% else %} 
        Products
    {% endif %}
{% endblock %}

{% block content %}

    <div class="container-fluid h-100" style="margin-top: 10%; margin-bottom: 10%">
    <div class="row">
        <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1" style="font-size: 24px; font-weight:300">
        {% for message in messages %}
            <p>{{ message }}</p>
        {% endfor %}
        <p style="font-size:60px; font-weight: 1000">Log In</p>
        <br>
          <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class='btn btn-default'>Login</button>
        </form>
        </div>
    </div>
    </div>
{% endblock %}

shop/templates/shop/navbar.html
<!DOCTYPE html>
{% load static %}
<nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom: 0px; background-color: #004d8c">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="container-fluid">
      <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{% url 'shop:product_list' %}" style="font-family: Cinzel Decorative; font-size: 24px; color: #ffffff">Pon Pon Chiao US Helpbuy</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'shop:story' %}" style="color: #ffffff; font-size: 24px"><strong>Our Story</strong></a></li>
        <li><a href="{% url 'shop:product_list' %}" style="color: #ffffff; font-size: 24px"><strong>Products</strong></a></li>
     </ul>

    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"  style="color: #ffffff; font-size: 24px" >Account <span class="caret"></span></a>
        <ul class="dropdown-menu">
          {% if not request.user.is_authenticated %}
          <li><a href="{% url 'shop:login' %}">Login</a></li>
          <li><a href="{% url 'shop:register' %}">Sign Up</a></li>
          {% else %}
          <li><a href="#" style="font-weight: 1200; color:#004d8c ">{{ request.user.username }}</a></li>
          <li><a href="{% url 'shop:logout' %}">Log Out</a></li>
          {%  endif %}

        </ul>
      </li>

    </ul>
  </div><!-- /.navbar-collapse -->
  </div>
</nav>

shop/templates/shop/signup.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
    {% if category %}
        {{ category.name }} 
    {% else %} 
        Products
    {% endif %}
{% endblock %}

{% block content %}

    <div class="container-fluid h-100" style="margin-top: 10%; margin-bottom: 10%">
    <div class="row">
        <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1" style="font-size: 24px; font-weight:300">
        <p style="font-size:60px; font-weight: 1000">Sign up</p>
            <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class='btn btn-default' type="submit">Sign up</button>
            </form>
        </div>
    </div>
    </div>
{% endblock %}

shop/templates/shop/story.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
    {% if category %}
        {{ category.name }} 
    {% else %} 
        Products
     {% endif %}
{% endblock %}


{% block content %}
<div class="container-fluid h-100">
<p style="font-weight: 600; font-size: 50px"> Testing for login required</p>
</div><!-- /.container -->
{% endblock %} 